language: cpp

os:
  - linux
  
dist: trusty

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++','libboost-filesystem-dev','libboost-program-options-dev']

install: 
    - cd bin
    - cmake ..
    
script:
    - make

