language: cpp

os:
  - linux
  - osx

dist: trusty  
group: edge

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['gfortran-7','libboost-filesystem-dev','libboost-program-options-dev']

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc;
    fi

  - export FC=gfortran-7

install: 
    - cd bin
    - cmake ..
    
script:
    - make

