language: cpp

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: CXX=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty']
          packages: ['clang-3.8']
      env: CXX=clang++-3.8

    - os: osx
      compiler: clang
      env: CXX=clang++


script: 
    - cd bin
    - cmake ..
    - make

