language: cpp

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - libboost-filesystem-dev
      - libboost-program-options-dev

compiler: 
    - gcc

script: 
    - cd bin
    - cmake ..
    - make

