language: cpp

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5','libboost-filesystem-dev','libboost-program-options-dev']
      env: CXX=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-3.8']
          packages: ['clang-3.8','libboost-filesystem-dev','libboost-program-options-dev']
      env: CXX=clang++-3.8

    - os: osx
      compiler: clang
      env: CXX=clang++


script: 
    - cd bin
    - cmake ..
    - make VERBOSE=1

