language: cpp

sudo: true
dist: trusty

notifications:
  email: false

git:
  depth: 1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty
    packages:
      - g++-5
      - clang-3.8
      - libboost-filesystem-dev
      - libboost-program-options-dev

compiler: 
    - gcc
    - clang

script: 
    - cd bin
    - cmake ..
    - make

