name: ci

on:
  push:
    paths:
      - "**.f90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci.yml"
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
